### ISSUE TITLE
data_frames error

### ISSUE THREAD

**Issue by dolugen** [masalmon/Ropenaq#10]
Hello @masalmon!

I'm trying the examples in `Readme.md` and possibly the nice vignettes you've been sharing on Twitter :smiley:

I have managed to install Ropenaq (total R newb myself) and getting some results. But, I can't get measurements and latest data. Could you take a look?

```R
> citiesTable <- aq_cities()
> countriesTable <- aq_countries()
> latestTable <- aq_latest()
Error: data_frames can only contain 1d atomic vectors and lists
> measurementsTable <- aq_measurements()
Error: data_frames can only contain 1d atomic vectors and lists
```
System info:
```
R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

Ropenaq version is probably this one: cf5617dc26d9b9482817a5e349ccadd2f75d2ef3

**Comment by masalmon** [comment]
Hi @dolugen !
I'm happy to see you want to use the R package. I'm a big fan of the interface of the API where I checked my package was giving the right numbers in the first stages. :smile:

Which version of dplyr do you have?

**Comment by masalmon** [comment]
And when did you install the Ropenaq package? Maybe install it again so we're sure we're testing the same version?

**Comment by dolugen** [comment]
My dplyr version is 0.4.3

OK, reinstalled from the latest master.

**Comment by masalmon** [comment]
If reinstalling Ropenaq doesn't solve the problem, maybe try also reinstalling dplyr from github
devtools::install_github("hadley/dplyr")

We're going to make it work on your PC, don't worry!

**Comment by dolugen** [comment]
After `install_github`, `dplyr` is updated to `0.4.3.9000`. And now `aq_measurements()` and `aq_latest()` works!

Thanks a lot for the help :+1:

**Comment by dolugen** [comment]
Issue resolved.

**Comment by masalmon** [comment]
Cool! I'm really glad it's working now! Don't hesitate to report on your experience. I guess you'll look at data from Mongolia?

**Comment by dolugen** [comment]
Yes, I'll see if I can reproduce your maps for Mongolia.

**Comment by masalmon** [comment]
Cool! It should be interesting! It would also be interesting to Tsenguun with whom I've talked on the Open AQ slack.

I've mentioned to her that I think that coupling OpenAQ data with data from Openstreetmap for Ulaanbaatar might be interesting.

**Comment by masalmon** [comment]
I should stop using the word "interesting"...

**Comment by masalmon** [comment]
FYI I copy here the code I've sent to Tsenguun (for making the two graphs about Ulaanbaatar I tweeted yesterday).

############################################################################
# load packages
############################################################################
# download this package from github
# https://github.com/masalmon/Ropenaq/
library("Ropenaq")

# for manipulating data frames
library("dplyr")

# for graphics
library("ggplot2")

# for graphics of air pollution
library("openair")

# for getting an alert when the analysis is finished
library("beepr")

# for manipulating dates
library("lubridate")

# find locations in Mongolia
aq_locations(city = "Ulaanbaatar")

############################################################################
# measures for Ulaanbaatar for CO
############################################################################
# I comment this and load the data I saved
# # extract all measures for Ulaanbaatar for CO
# aq_measurements(city = "Ulaanbaatar", parameter = "co")
#
# # we'll need several calls to the API because there are many measurements
# measurementsCO <- NULL
# for (page in 1:79){
#   print(page)
#   measurementsCO <- rbind(measurementsCO,
#                           aq_measurements(city = "Ulaanbaatar",
#                                           parameter = "co",
#                                           limit = 1000,
#                                           page = page))
# }
# save(measurementsCO, file = "measurementsCO.RData")
# beep()
load("measurementsCO.RData")

############################################################################
# Play with the data
############################################################################
# Filter negative values
measurementsCO <- filter(measurementsCO,
                         value > 0)
# Rename CO parameter and date and find month
measurementsCO <- mutate(measurementsCO,
                         CO = value,
                         date = dateLocal,
                         month = month(dateLocal))

# Plot
ggplot(measurementsCO) + geom_point(aes(x = dateLocal,
                                        y = CO,
                                        col = location))+
  ylab(expression(paste("CO concentration (", mu, "g/",m^3,")"))) +
  facet_grid(location ~ .)

# Plot with openair package
GoogleMapsPlot(as.data.frame(measurementsCO),
               lat = "latitude", long = "longitude",
               pollutant = "CO", cex=2,
               maptype = "roadmap", col = "jet")

**Comment by dolugen** [comment]
> Where can I find your email address?
You can find it on my profile page (made public for now).

**Comment by masalmon** [comment]
cool, I've sent you an email!
