### ISSUE TITLE
use memoise

### ISSUE THREAD

**Issue by masalmon** [masalmon/Ropenaq#16]
thanks to @hrbrmstr I now know about memoise for creating a cache for each session. I need to add it to the pkg, this way when I ask all cities for the first time in a session results get cached and the next time in the same session I will gain time.

**Comment by jflasher** [comment]
Sounds awesome! I guess one thing to be careful of is that if the session is long enough (> 10 minutes), they data will become stale since that's our data update time. Might be useful to save your cache time and then check `fetches?limit=1` and see if the last fetch time is before or after your cache time to know if you need to dump it.

**Comment by masalmon** [comment]
Oh yes you're right! But what if I only use caching for countries, cities and locations? Then even with a long session it'd probably be ok, right?

**Comment by jflasher** [comment]
Depends on what info you're getting from them. If it's just the names, it should be fine, but does have a low likelihood of changing. The counts would be wrong though. For locations, last updated and counts would be off.

**Comment by masalmon** [comment]
Oh yes you're right, this could be important for things that are not the checks in utils.R 
So I should write a warning in the documentation, and put cache = FALSE as a default for end users.

**Comment by masalmon** [comment]
I'm into "oh yes you're right" apparently but you WERE right ah ah.

**Comment by masalmon** [comment]
(I promise I don't have an automatic answer to all my issues!)

**Comment by jflasher** [comment]
Haha, no worries, it beats the alternative!

**Comment by masalmon** [comment]
In memoise there is a timeout argument, in seconds. @jflasher would these values make sense?

* countries 60*60

* cities 60*60

* locations 60*60

* latest 10*60

* measurements 10*60

?

**Comment by masalmon** [comment]
My current plan is:

* export memoised functions instead of the non memoised functions for all endpoints, with the timeout values as speficied above.

* in the doc, mention I used memoization and that one can use memoise::forget for erasing all cached values.

* make a document about using memoise for other memoise beginners.

**Comment by jflasher** [comment]
For the timeout, it's a bit hard to say. If you hit the API 1 second before it updates, your data will be out of date for the next 9:59. Not sure how much control you have over memoise, but if you want caching and access to the latest data, you could check for the responses Last-Modified date. You can see an example of this below.

```sh
$ curl -I 'https://api.openaq.org/v1/measurements'
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Mon, 04 Apr 2016 14:19:27 GMT
Last-Modified: Mon, 04 Apr 2016 14:09:51 GMT
```

You could potentially make an `options` request to get the last-modified (this should be very quick) and then use your cache if your data is newer. If your data is older, you could do the full request to get the data.

Otherwise, I might shorten your timeouts a little to not miss new data coming in.

**Comment by masalmon** [comment]
The last-modified is only available for measurements and latest, right?

So maybe I should simply have a memoised version for cities/locations/countries and let measurements and latest as they are?

**Comment by jflasher** [comment]
All endpoints should be returning the same last-modified value since it's really the last modified time of the whole dataset.

**Comment by masalmon** [comment]
When I open https://api.openaq.org/v1/cities in my browser, I don't see last modified in the meta, is this a bug?

**Comment by jflasher** [comment]
Nope, this is expected. It's not a property in the JSON data, it's actually something in the response headers which is what I'm getting when I do the `curl -I` like in the above example. I'm not familiar with how R handles these types of requests, so not sure what you have access to internally.

**Comment by masalmon** [comment]
ok I will try to see to it!

**Comment by masalmon** [comment]
I have given it more thought and I think I'm simply going to remove the memoise thing, this way I'm sure to get the latest results. Might be slower, but it's safer too...

I'm now working on a version where I output the last-modified timestamp, though. :-)
